### PR TITLE
Ported to .NET Core and replaced Logger

### PR DESCRIPTION
**Pull request by g0df4ther**

### CODE REVIEW

**Comment by dotmbf** [comment]
what is serilog and what is the benefits from moving to that from log4net?

**Comment by g0df4ther** [comment]
> 
> 
> what is serilog and what is the benefits from moving to that from log4net?

A logging library like log4net, tried a lot diagnostic logging libraries in the past and Serilog is by far the best in my opinion.
Benefits would be structured logging (by default), enrichment, performance and C# based configuration.

**Comment by dotmbf** [comment]
I don't really see the 'ported to .net core' stuff, what exactly do you mean by this? Seems like it's just entirely the same, change to be using serilog

**Comment by g0df4ther** [comment]
- Converted packages.config dependencies to PackageReference format via VS.
- Modified [Plus Emulator.csproj](https://github.com/Sledmore/PlusEMU/pull/13/commits/4168382ee67749cd3d5696e95d13b0a3fe50d785#diff-5d9e899e864fe2176ec3c582847032b5) and removed no longer needed stuff.
- File removals: packages.config (converted), app.config (was only used for log4net), Properties/Settings.settings,  Properties/Settings.Designer.cs, Properties/AssemblyInfo.cs (With .NET Core, the metadata is saved in the project file as standard)

In addition, only 2 lines had to be adjusted in PlusEnvironment.cs and Core/FigureData/FigureDataManager.cs because of not producing the same result in .NET Core. (Path Syntax)

.NET Portability Analyzer will confirm that there is nothing else to consider, everything works for me as expected.

**Pull request closed without merging**
